import { UserProvider } from "@/contextData/ContextData";
import "./globals.css";
import ProviderSetup from "@/store/ProviderSetup";
import Header from "@/components/Header";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const randomNumber = Math.random()
  console.log(randomNumber);


  if (randomNumber > 0.5) {
    throw new Error("globel root error")
  }
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <ProviderSetup>
            <Header />
            {children}
          </ProviderSetup>
        </UserProvider>
      </body>
    </html>
  );
}
