import { UserProvider } from "@/contextData/ContextData";
import "./globals.css";
import ProviderSetup from "@/store/ProviderSetup";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <ProviderSetup>
            {children}
          </ProviderSetup>
        </UserProvider>
      </body>
    </html>
  );
}
